default_platform(:android)

platform :android do

     lane :generate_apk do |options|

       gradle(
           task: "clean assemble",
           flavor: options[:flavor],
           build_type: options[:build_type])

     end


     lane :generate_signed_apk do |options|

        gradle(
            task: "clean assemble",
            build_type: options[:build_type],
            print_command: true,
            properties: {
                "android.injected.signing.store.file" => options[:keystore_path],
                "android.injected.signing.store.password" => options[:store_password],
                "android.injected.signing.key.alias" => options[:key_alias],
                "android.injected.signing.key.password" => options[:key_password]})
      end

     lane :run_unit_tests do
        gradle(task: "test")
     end

end