default_platform(:android)

platform :android do

     lane :generate_apk do |options|

       gradle(
           task: "clean assemble",
           flavor: options[:flavor],
           build_type: options[:build_type])

     end


     lane :generate_signed_apk do |options|

        gradle(
            task: "clean assemble",
            build_type: options[:build_type],
            print_command: true,
            properties: {
                "android.injected.signing.store.file" => options[:keystore_path],
                "android.injected.signing.store.password" => options[:store_password],
                "android.injected.signing.key.alias" => options[:key_alias],
                "android.injected.signing.key.password" => options[:key_password]})
      end

     lane :run_lint do
        gradle(task: "lint")
     end

     lane :run_unit_tests do
        gradle(task: "test")
     end

     lane :deploy_apk_to_play_store do |options|
        upload_to_play_store(
            track: "internal",
            apk: "app/build/outputs/apk/release/release.apk",
            json_key: options[:service_account_json_path],
            skip_upload_images:true,
            skip_upload_screenshots:true)
     end

end